# Generated by Django 4.1.13 on 2026-03-21 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_created_at_event_created_by_eventregistration_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='event',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('volunteer', 'event_id')},
        ),
    ]
